@@ -25,86 +25,88 @@
prefix = @prefix@
exec_prefix = @exec_prefix@
datarootdir = @datarootdir@
# Pathname of directory to install the configure program
bindir = @bindir@
# Pathname of directory to install the rpcapd daemon
sbindir = @sbindir@
# Pathname of directory to install the include files
includedir = @includedir@
# Pathname of directory to install the library
libdir =  @libdir@
# Pathname of directory to install the man pages
mandir = @mandir@

# VPATH
srcdir = @srcdir@
top_srcdir = @top_srcdir@
VPATH = @srcdir@

#
# You shouldn't need to edit anything below.
#

LD = /usr/bin/ld
CC = @CC@
CXX = @CXX@
AR = @AR@
LN_S = @LN_S@
MKDEP = @MKDEP@
CCOPT = @V_CCOPT@
INCLS = -I. -I.. -I@srcdir@ -I@srcdir@/.. @V_INCLS@
DEFS = @DEFS@ @V_DEFS@
ADDLOBJS = @ADDLOBJS@
ADDLARCHIVEOBJS = @ADDLARCHIVEOBJS@
LIBS = @LIBS@
PTHREAD_LIBS = @PTHREAD_LIBS@
CROSSFLAGS=
CFLAGS = @CFLAGS@   ${CROSSFLAGS}
LDFLAGS = @LDFLAGS@ ${CROSSFLAGS}
DYEXT = @DYEXT@
V_RPATH_OPT = @V_RPATH_OPT@
DEPENDENCY_CFLAG = @DEPENDENCY_CFLAG@

# Standard CFLAGS for building test programs
FULL_CFLAGS = $(CCOPT) $(INCLS) $(DEFS) $(CFLAGS)

INSTALL = @INSTALL@
INSTALL_PROGRAM = @INSTALL_PROGRAM@
INSTALL_DATA = @INSTALL_DATA@

.c.o:
	$(CC) $(FULL_CFLAGS) -c -o $@ $<

SRC = @VALGRINDTEST_SRC@ \
	activatetest.c \
	can_set_rfmon_test.c \
	capturetest.c \
	filtertest.c \
	findalldevstest-perf.c \
	findalldevstest.c \
	opentest.c \
	nonblocktest.c \
	sniffer_report.c \
	reactivatetest.c \
	selpolltest.c \
	threadsignaltest.c \
	translatetest.c \
	versiontest.c \
	writecaptest.c

TESTS = $(SRC:.c=)

TAGFILES = \
	$(SRC) $(HDR)

CLEANFILES = $(OBJ) $(TESTS)

all: $(TESTS)

# illumos make is the only known supported make that would expand "$<" below
# into "../libpcap.a" instead of "$(srcdir)/xxxxxxxx.c ../libpcap.a".

activatetest: $(srcdir)/activatetest.c ../libpcap.a
	$(CC) $(FULL_CFLAGS) -I. -L. -o $@ $(srcdir)/activatetest.c \
	    ../libpcap.a $(LIBS)

capturetest: $(srcdir)/capturetest.c ../libpcap.a
	$(CC) $(FULL_CFLAGS) -I. -L. -o $@ $(srcdir)/capturetest.c \
@@ -115,50 +117,54 @@ can_set_rfmon_test: $(srcdir)/can_set_rfmon_test.c ../libpcap.a
	    $(srcdir)/can_set_rfmon_test.c \
	    ../libpcap.a $(LIBS)

filtertest: $(srcdir)/filtertest.c ../libpcap.a
	$(CC) $(FULL_CFLAGS) -I. -L. -o $@ $(srcdir)/filtertest.c \
	    ../libpcap.a $(LIBS)

findalldevstest: $(srcdir)/findalldevstest.c ../libpcap.a
	$(CC) $(FULL_CFLAGS) -I. -L. -o $@ \
	    $(srcdir)/findalldevstest.c \
	    ../libpcap.a $(LIBS)

findalldevstest-perf: $(srcdir)/findalldevstest-perf.c ../libpcap.a
	$(CC) $(FULL_CFLAGS) -I. -L. -o $@ \
	    $(srcdir)/findalldevstest-perf.c \
	    ../libpcap.a $(LIBS)

opentest: $(srcdir)/opentest.c ../libpcap.a
	$(CC) $(FULL_CFLAGS) -I. -L. -o $@ $(srcdir)/opentest.c \
	    ../libpcap.a $(LIBS)

nonblocktest: $(srcdir)/nonblocktest.c ../libpcap.a
	$(CC) $(FULL_CFLAGS) -I. -L. -o $@ $(srcdir)/nonblocktest.c \
	    ../libpcap.a $(LIBS)

sniffer_report: $(srcdir)/sniffer_report.c ../libpcap.a
	$(CXX) $(FULL_CFLAGS) -x c++ -I. -L. -o $@ $(srcdir)/sniffer_report.c \
	    ../libpcap.a $(LIBS)

reactivatetest: $(srcdir)/reactivatetest.c ../libpcap.a
	$(CC) $(FULL_CFLAGS) -I. -L. -o $@ \
	    $(srcdir)/reactivatetest.c ../libpcap.a $(LIBS)

selpolltest: $(srcdir)/selpolltest.c ../libpcap.a
	$(CC) $(FULL_CFLAGS) -I. -L. -o $@ $(srcdir)/selpolltest.c \
	    ../libpcap.a $(LIBS)

threadsignaltest: $(srcdir)/threadsignaltest.c ../libpcap.a
	$(CC) $(FULL_CFLAGS) -I. -L. -o $@ \
	    $(srcdir)/threadsignaltest.c \
	    ../libpcap.a $(LIBS) $(PTHREAD_LIBS)

translatetest: $(srcdir)/translatetest.c ../libpcap.a
	$(CC) $(FULL_CFLAGS) -I. -L. -o $@ $(srcdir)/translatetest.c \
	    ../libpcap.a $(LIBS)

valgrindtest: $(srcdir)/valgrindtest.c ../libpcap.a
	$(CC) $(FULL_CFLAGS) -I. -L. -o $@ $(srcdir)/valgrindtest.c \
	    ../libpcap.a $(LIBS)

versiontest: $(srcdir)/versiontest.c ../libpcap.a
	$(CC) $(FULL_CFLAGS) -I. -L. -o $@ $(srcdir)/versiontest.c \
	    ../libpcap.a $(LIBS)
